# fly.toml file generated for greeting-card-magic on 2023-04-15T21:44:02-04:00

app = "greeting-card-magic"
primary_region = "dfw"

[http_service]
  internal_port = 8081
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[env]
  NODE_ENV="production"
  PORT = "8081"
  HOST = "https://greeting-card-magic.fly.dev"
  SHOPIFY_API_KEY="fbf2d5b8d879e08d5df47a813df4c65f"
  SCOPES = "write_products"
  app_name = "greeting-card-magic"
